
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /opt/app/node_modules
      - .:/opt/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    command: ["yarn", "test"]
